### ISSUE TITLE
1.18.2 Compat issue

### ISSUE THREAD

**Issue by Milkface100** [TheCosmicNebula/CosmosPortals#10]
A combination of CC:Tweaked, Immersive engineering, and CosmosPortals causes a crash when opening a portal, i have no idea why it does this, it just does.

[crash-2024-11-19_06.18.54-client.txt](https://github.com/user-attachments/files/17814348/crash-2024-11-19_06.18.54-client.txt)

(First time making a bug report like this, please tell me if i did something wrong)

**Comment by TheCosmicNebula** [comment]
Hi, thanks for your issue report, unfortunately the 1.18.2 version of Cosmos Portals is no longer supported.
