### ISSUE TITLE
[SUGGESTION]: Make Portal frames full brightness

### ISSUE THREAD

**Issue by SrRapero720** [TheCosmicNebula/CosmosPortals#5]
Making brightness full can make more imponent portals. 
also with shaders looks so cool

**SIMULATION WITH NIGHT VISION**
![2022-09-16_16h40_23](https://user-images.githubusercontent.com/29090346/190794133-839f5da4-7170-43da-bd2b-6a81011c64b3.png)

**BORED PORTAL WITHOUT NIGHT VISION**
note: actual bright in the portal comes from the sea lantern.
![2022-09-16_16h40_38](https://user-images.githubusercontent.com/29090346/190795258-8d526504-b277-4965-b2e1-760cffd13ec2.png)

**Comment by TheCosmicNebula** [comment]
This is a good idea, I will implement it for the next release of ComsosPortals for 1.19.1

**Comment by SrRapero720** [comment]
**Plz** consider to add into 1.18.2 so.
1.19.1 scares me, and scares my account (without mentioning i'll running a server using 1.18.2).

**Comment by TheCosmicNebula** [comment]
Implemented in versions: 1.18.2-4.1.0.20 & 1.19.2-6.1.0.0
