### ISSUE TITLE
[1.18.2] Repeat of earlier issue - incompatibility with Ultimate Car Mod

### ISSUE THREAD

**Issue by JDtheHutt** [TheCosmicNebula/CosmosPortals#7]
This appears to be a repeat of an earlier issue as my log looks the same as the previous one reported, only with newer versions involved.  It was reported as fixed under [https://github.com/TheCosmicNebula/CosmosPortals/issues/4](url).  Please see my log below.  Love your mods by the way!  The kids want the car one but they will be disappointed if I have to make a choice.  Thank you.

[crash-2022-11-13_21.39.13-client.txt](https://github.com/TheCosmicNebula/CosmosPortals/files/9998280/crash-2022-11-13_21.39.13-client.txt)

**Comment by TheCosmicNebula** [comment]
Hi, I do not know how I missed this! This issue was should have been fixed, it was due to a registration error. Please let me know (if you are still using the mod) whether this is still broken.

And thanks! 😊
