### ISSUE TITLE
1.19.2 Can't put container in portal.

### ISSUE THREAD

**Issue by PercyJames** [TheCosmicNebula/CosmosPortals#8]
I've tried right clicking, left clicking, shift right clicking, putting it in the slot manually but nothing is working.

**Comment by PercyJames** [comment]
I also changed the UI lock state to public but that didn't work.

**Comment by TheCosmicNebula** [comment]
Silly question, but have you:

1. Linked the Container to a location,
2. Ensured the portal is fully enclosed (Full circle),
3. Have an empty off-hand when you try to put the Container in the Dock;

**Comment by PercyJames** [comment]
Ok so, I turns out this is a problem I faced before. I fixed it. there's no bug.

**Comment by TheCosmicNebula** [comment]
Is this issue resolved? You have re-opened it.

**Comment by PercyJames** [comment]
yes. It is resolved. No idea why I reopend it. I'll close it now.
