### ISSUE TITLE
[1.19.2] Game crash when right clicking the portal dock

### ISSUE THREAD

**Issue by KakadoMan** [TheCosmicNebula/CosmosPortals#9]
Im on the 1.19.2 version of minecraft with this mod and other mods and every time i crouch right click the portal dock my game crashes. It doesnt matter if theres an item in my hand or not, it still crashes. When just right clicking the dock the GUI of the dock pops up and works normal. This happens any time and i dont really know how to fix it. I'll leave the crash and log text documents here as ordered.

[crash-2024-02-22_21.39.32-client.txt](https://github.com/CosmosMods/CosmosPortals/files/14379189/crash-2024-02-22_21.39.32-client.txt)
[latest.log](https://github.com/CosmosMods/CosmosPortals/files/14379192/latest.log)

**Comment by AkariEnderwolf** [comment]
I'm having the same issue of crashes on 1.19.2
It happens whenever I shift+right click the portal dock.

[crash-2024-04-12_18.32.20-client.txt](https://github.com/CosmosMods/CosmosPortals/files/14964202/crash-2024-04-12_18.32.20-client.txt)
[latest.log](https://github.com/CosmosMods/CosmosPortals/files/14964204/latest.log)

**Comment by BlueDuckYT** [comment]
Also having this issue

**Comment by TheCosmicNebula** [comment]
Sorry for the very late response guys. It is an issue with Capabilities and the Botarium mod. I will see what I can do in the coming weeks.
